#!/usr/bin/env bash
#
# Idempotent one-time setup for the caddy-system Cloud Agent environment.
# Runs after the repository is checked out. Prepares durable state only:
#   - installs PostgreSQL (system dependency)
#   - creates the local dev role/database
#   - writes a local .env with dev defaults (gitignored)
#   - installs npm dependencies (postinstall runs `prisma generate`)
#
# Per-boot work (starting Postgres, applying migrations, seeding) lives in
# .cursor/start.sh so it re-runs on every boot.
set -euo pipefail

cd "$(dirname "$0")/.."

DB_USER="caddy"
DB_PASSWORD="caddy"
DB_NAME="caddy"

echo "==> Ensuring PostgreSQL is installed"
if ! command -v pg_lsclusters >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-contrib
fi

# Resolve the installed major version + cluster name (usually 16 / main).
PG_VERSION="$(pg_lsclusters -h | awk 'NR==1{print $1}')"
PG_CLUSTER="$(pg_lsclusters -h | awk 'NR==1{print $2}')"
echo "==> Using PostgreSQL cluster ${PG_VERSION}/${PG_CLUSTER}"

echo "==> Ensuring the cluster is running (needed to create role/db)"
if ! pg_lsclusters -h | awk 'NR==1{print $4}' | grep -q online; then
  sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start
fi

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Ensuring dev role and database exist"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}' CREATEDB;"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

echo "==> Writing .env (local dev defaults) if missing"
if [ ! -f .env ]; then
  cat > .env <<'EOF'
# Local development defaults generated by .cursor/install.sh
DATABASE_URL="postgresql://caddy:caddy@localhost:5432/caddy?schema=public"

# NextAuth (credentials provider backed by the User table)
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="dev-only-secret-not-for-production"

# Simple cookie login (/api/login) + shared caddy account
ADMIN_USER="admin"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD="admin1234"
CADDY_USER="caddy"
CADDY_USERNAME="caddy"
CADDY_PASSWORD="caddy1234"
EOF
fi

echo "==> Installing npm dependencies"
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "==> install.sh complete"
