#!/usr/bin/env bash
#
# Cloud Agent environment install step for caddy-system.
#
# Durable, idempotent repository bootstrap that is baked into the environment
# snapshot: selects Node, provisions the local Postgres role/database, writes a
# local-only .env, installs npm dependencies and generates the Prisma client.
#
# Per-boot reconciliation (cluster start, prisma migrate deploy, seed, demo
# import) lives in scripts/cloud-agent-start.sh instead.
#
# This script mirrors the dashboard-managed environment "install" command. Keep
# the two in sync.
set -euo pipefail

cd "$(cd "$(dirname "$0")/.." && pwd)"

echo "==> Selecting Node 24 via nvm"
export NVM_DIR="$HOME/.nvm"
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm install 24 >/dev/null 2>&1 || true
nvm alias default 24 >/dev/null 2>&1 || true
nvm use default >/dev/null 2>&1 || true
echo "    node $(node -v) / npm $(npm -v)"

echo "==> Ensuring local PostgreSQL cluster 16/main is running"
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do pg_isready -h localhost -p 5432 >/dev/null 2>&1 && break; sleep 1; done

echo "==> Ensuring local 'caddy' role and database exist"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='caddy'" | grep -q 1; then
  sudo -u postgres psql -c "CREATE ROLE caddy LOGIN PASSWORD 'caddy';"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='caddy'" | grep -q 1; then
  sudo -u postgres createdb -O caddy caddy
fi

echo "==> Ensuring local-only .env exists"
if [ ! -f .env ]; then
  cat > .env <<EOF
# Local development defaults generated by the Cloud Agent environment install step
DATABASE_URL="postgresql://caddy:caddy@localhost:5432/caddy?schema=public"

# NextAuth (credentials provider backed by the User table)
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="$(openssl rand -hex 32)"

# Simple cookie login (/api/login) + shared caddy account
ADMIN_USER="admin"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD="admin1234"
CADDY_USER="caddy"
CADDY_USERNAME="caddy"
CADDY_PASSWORD="caddy1234"
EOF
  echo "    wrote local .env"
else
  echo "    .env already present, leaving it untouched"
fi

echo "==> Installing npm dependencies (postinstall runs prisma generate)"
npm ci

echo "==> install complete"
